### ISSUE TITLE
Flow-CLI 安装成功，flow 命令并未注册上

### ISSUE THREAD

**Issue by nianlee** [tower1229/Flow-CLI#1]
## 1、安装成功，截图如下
<img width="1279" alt="wx20171120-221124 2x" src="https://user-images.githubusercontent.com/13048585/33022346-d7798820-ce3f-11e7-81d9-f41382cf5065.png">

## 2、flow命令并未找到，截图如下

<img width="397" alt="wx20171120-221451 2x" src="https://user-images.githubusercontent.com/13048585/33022466-4ebd317a-ce40-11e7-9af0-5db96ab0bf45.png">

**Comment by tower1229** [comment]
与依赖包的版本没有关系，我这里没有复现问题，你执行`npm link`试试，参考这里：http://www.ruanyifeng.com/blog/2015/05/command-line-with-node.html

**Comment by nianlee** [comment]
@tower1229 谢谢，我在下载的flow-cli项目里面，执行 `npm link`，命令注册成功了。
