### ISSUE TITLE
修改js文件，没有重新编译

### ISSUE THREAD

**Issue by nianlee** [tower1229/Flow-CLI#2]
https://github.com/flow-ui/Flow-CLI/blob/dd0f20cdc49d7dd1ae399c6dd3b3d3fd4c18689e/bin/build.js#L321

### 问题描述
1. 系统环境mac
2. debug 发现 filePath 的格式为  "_src/js/demo.js"，而源码里面的检索的格式为"\js\"。这里的分隔符反了，不知是否与系统有关。

**Comment by nianlee** [comment]
@tower1229 感谢这么快就修复了，发现了两个小问题
### 1 修复产生的新问题
https://github.com/flow-ui/Flow-CLI/blob/1f8a7dab06d8feb72d7217bc09541b50ef745822/bin/build.js#L387

这里的 Path4OS 未定义

### 2 css 编译深层目录问题
https://github.com/flow-ui/Flow-CLI/blob/1f8a7dab06d8feb72d7217bc09541b50ef745822/bin/build.js#L411
这里编译产出的css 只能是一级目录，对于深层目录有点问题。下面这个匹配文件路径的正则忘采纳
```
let getpathreg = new RegExp(globalConfig.projectDir + '(.+)\\/[^\\.]+\\.[^\\.]+');
```

**Comment by tower1229** [comment]
@nianlee 第一个问题是我手残，随后已经改掉了；第二个问题您直接提交PR吧

**Comment by nianlee** [comment]
@tower1229 - - 还在学习中，对于widget的缓存这一块，看得不是很明白，多个widget合并后，每次修改script需要整个重新编译才能生效。widget的读取和赋值耦合在一块了，我尝试改改，非常感谢大佬的分享。
